from pydoppler.core import HTTP


class Doppler(HTTP):
    def __init__(self, token: str) -> None:...
    def retrieve_workspace(self) -> dict:...
    def update_workspace(self, name: str, billing_email: str) -> dict:...
    def fetch_projects(self, page: int = ..., per_page: int = ...) -> dict:...