from calendar import c


class API:
    ROOT_URL = 'https://api.doppler.io/v3'

    @classmethod
    def workspace(cls) -> str:...
    
    @classmethod
    def activity_logs(cls, page: int, per_page: int) -> list[str, dict[str, int]]:...    

    @classmethod
    def activity_logs_retrieve(cls, log_id: str) -> list[str, dict[str, str]]:...

    @classmethod
    def projects(cls) -> list[str, dict[str, int]]:...

    @classmethod
    def projects_create(cls, name: str, description: str) -> list[str, dict[str, str]]:...

    @classmethod
    def projects_retrieve(cls, project_name: str) -> list[str, dict[str, str]]:...

    @classmethod
    def projects_update(cls, project_name: str, project_new_name: str, description: str) -> list[str, dict[str, str]]:...

    @classmethod
    def projects_delete(cls, project_name: str) -> list[str, dict[str, str]]:...

    @classmethod
    def environments(cls, project_name: str) -> list[str, dict[str, str]]:...

    @classmethod
    def environments_retrieve(cls, project_name: str, environment: str) -> list[str, dict[str, str]]:...

    @classmethod
    def environments_create(cls, project_name: str, name: str, slug: str) -> list[str, dict[str, str], dict[str, str]]:...

    @classmethod
    def environments_delete(cls, project_name: str, environment: str) -> list[str, dict[str, str]]:...

    @classmethod
    def environments_rename(cls, project_name: str, environment: str, name: str, slug: str) -> list[str, dict[str, str], dict[str, str]]:...

    @classmethod
    def configs(cls, project_name: str, page: int, per_page: int) -> list[str, dict[str, int]]:...
    
    @classmethod
    def configs_create(cls, project_name: str, environment: str, config_name: str) -> list[str, dict[str, str]]:...
    
    @classmethod
    def configs_retrieve(cls, project_name: str, config_name: str) -> list[str, dict[str, str]]:...
    
    @classmethod
    def configs_update(cls, project_name: str, config_name: str, config_new_name: str) -> list[str, dict[str, str]]:...
    
    @classmethod
    def configs_delete(cls, project_name: str, config_name: str) -> list[str, dict[str, str]]:...
    
    @classmethod
    def configs_clone(cls, project_name: str, config_name: str, config_new_name: str) -> list[str, dict[str, str]]:...
    
    @classmethod
    def configs_lock(cls, project_name: str, config_name: str) -> list[str, dict[str, str]]:...   

    @classmethod
    def configs_unlock(cls, project_name: str, config_name: str) -> list[str, dict[str, str]]:...    
 
    @classmethod
    def configs_logs(cls, project_name: str, config_name: str, page: int, per_page: int) -> list[str, dict[str, str | int]]:...
    
    @classmethod
    def configs_logs_retrieve(cls, project_name: str, config_name: str, log_id: str) -> list[str, dict[str, str]]:...
    
    @classmethod
    def configs_logs_rollback(cls, project_name: str, config_name: str, log_id: str) -> list[str, dict[str, str]]:...

